# Generated by Django 5.1.3 on 2024-11-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_delete_customuser"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="doctors",
            fields=[
                (
                    "doctorId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("activePatient", models.CharField(max_length=50, null=True)),
                ("finishedPatients", models.JSONField(null=True)),
                ("remainingPatients", models.JSONField(null=True)),
            ],
        ),
    ]
