# Generated by Django 5.1.3 on 2024-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctors",
            old_name="doctorId",
            new_name="doctorID",
        ),
        migrations.RemoveField(
            model_name="doctors",
            name="remainingPatients",
        ),
        migrations.AddField(
            model_name="doctors",
            name="allPatients",
            field=models.JSONField(null=True),
        ),
    ]
