# Generated by Django 5.1.3 on 2024-12-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_doctorid_doctors_doctorid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctors",
            old_name="allPatients",
            new_name="remainingPatients",
        ),
    ]
