# Generated by Django 5.1.3 on 2024-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_allpatients_doctors_remainingpatients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("mediaID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("url", models.TextField()),
            ],
        ),
    ]
