# Generated by Django 5.1.3 on 2024-12-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_media"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Media",
        ),
        migrations.RemoveField(
            model_name="doctors",
            name="remainingPatients",
        ),
    ]
