# Generated by Django 5.1.3 on 2025-01-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_delete_media_remove_doctors_remainingpatients"),
        ("image", "0014_merge_20241217_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="continueDiag",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.diagnosis",
            ),
        ),
    ]
