# Generated by Django 5.1.3 on 2025-01-08 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_doctors_continuediag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctors",
            name="activePatient",
        ),
    ]
