# Generated by Django 5.1.3 on 2025-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctors_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='finishedPatients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
