# Generated by Django 5.1.3 on 2025-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_doctors_finishedpatients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="finishedPatients",
            field=models.JSONField(null=True),
        ),
    ]
