# Generated by Django 5.1.3 on 2025-03-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_doctors_finishedpatients'),
        ('image', '0023_lesions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='continueDiag',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.diagnosis'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='finishedPatients',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
