# Generated by Django 5.1.3 on 2025-03-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_doctors_continuediag_and_more 2'),
        ('accounts', '0013_alter_doctors_continuediag_and_more'),
    ]

    operations = [
    ]
