# Generated by Django 5.1.3 on 2025-03-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20250321_1535'),
        ('accounts', '0017_alter_doctors_continuediag'),
    ]

    operations = [
    ]
