# Generated by Django 5.1.3 on 2025-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20250329_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='continueDiag',
            field=models.JSONField(null=True),
        ),
    ]
