# Generated by Django 5.1.3 on 2025-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_alter_doctors_continuediag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="continueDiag",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
