# Generated by Django 5.1.3 on 2024-11-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('diagID', models.AutoField(primary_key=True, serialize=False)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='useTime',
            fields=[
                ('timeID', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('timestamp', models.DurationField()),
                ('diagID', models.ForeignKey(db_column='diagID', on_delete=django.db.models.deletion.CASCADE, to='image.diagnosis')),
            ],
        ),
    ]
