# Generated by Django 5.1.3 on 2024-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='subID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
