# Generated by Django 5.1.3 on 2024-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_diagnosis_subid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='subID',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
