# Generated by Django 5.1.3 on 2024-12-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
        ("image", "0003_alter_diagnosis_confidence_alter_diagnosis_subid"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="urlToPicture",
            field=models.CharField(default="Unknown", max_length=10),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="userID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.doctors"
            ),
        ),
    ]
