# Generated by Django 5.1.3 on 2024-12-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0004_diagnosis_urltopicture_alter_diagnosis_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosis",
            name="subID",
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="urlToPicture",
            field=models.CharField(default="Unknown", max_length=20),
        ),
    ]
