# Generated by Django 5.1.3 on 2024-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0005_remove_diagnosis_subid_alter_diagnosis_urltopicture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnosis",
            old_name="userID",
            new_name="doctorID",
        ),
        migrations.RenameField(
            model_name="diagnosis",
            old_name="urlToPicture",
            new_name="imageUrl",
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="diagID",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
