# Generated by Django 5.1.3 on 2024-12-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_allpatients_doctors_remainingpatients"),
        ("image", "0007_rename_doctorid_diagnosis_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.doctors"
            ),
        ),
    ]
