# Generated by Django 5.1.3 on 2024-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0008_alter_diagnosis_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("mediaID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("url", models.TextField()),
            ],
        ),
    ]
