# Generated by Django 5.1.3 on 2024-12-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='editedDiagConfidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
