# Generated by Django 5.1.3 on 2024-12-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_remove_usetime_action_remove_usetime_timeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usetime',
            name='diagID',
            field=models.ForeignKey(db_column='diagID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='image.diagnosis', unique=True),
        ),
    ]
