# Generated by Django 5.1.3 on 2024-12-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_alter_usetime_diagid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usetime',
            name='diagID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='image.diagnosis'),
        ),
    ]
