# Generated by Django 5.1.3 on 2024-12-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_alter_usetime_diagid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usetime',
            name='diagID',
        ),
        migrations.AddField(
            model_name='usetime',
            name='diag',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='image.diagnosis'),
        ),
    ]
