# Generated by Django 5.1.3 on 2024-12-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_diagnosis_editeddiagconfidence'),
        ('image', '0013_remove_usetime_diagid_usetime_diag'),
    ]

    operations = [
    ]
