# Generated by Django 5.1.3 on 2025-01-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0014_merge_20241217_1545"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnosis",
            old_name="imageUrl",
            new_name="imageURL",
        ),
    ]
