# Generated by Django 5.1.3 on 2025-01-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0015_rename_imageurl_diagnosis_imageurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="mediaParent",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.media",
            ),
        ),
    ]
