# Generated by Django 5.1.3 on 2025-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0016_diagnosis_mediaparent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
