# Generated by Django 5.1.3 on 2025-01-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0017_alter_media_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnosis",
            old_name="mediaParent",
            new_name="mediaFolder",
        ),
    ]
