# Generated by Django 5.1.3 on 2025-01-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0018_rename_mediaparent_diagnosis_mediafolder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="mediaFolder",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.media",
            ),
        ),
    ]
