# Generated by Django 5.1.3 on 2025-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0019_alter_diagnosis_mediafolder"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="confidenceOfAIdiag",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="confidence",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="confidenceOfEditedDiag",
            field=models.JSONField(null=True),
        ),
    ]
