# Generated by Django 5.1.3 on 2025-01-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_doctors_datasets"),
        ("image", "0020_diagnosis_confidenceofaidiag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="confidence",
            field=models.JSONField(
                null=True, verbose_name="Confidence for the marked lesions"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="confidenceOfAIdiag",
            field=models.JSONField(
                null=True, verbose_name="Confidence to take the AI Diagnosis"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="confidenceOfEditedDiag",
            field=models.JSONField(
                null=True,
                verbose_name="Confidence for the lessions after seeing AI Diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="diagID",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Diagnosis ID",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.doctors",
                verbose_name="Diagnosing doctor",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="imageURL",
            field=models.CharField(
                default="Unknown", max_length=20, verbose_name="Url to the picture"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="mediaFolder",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.media",
                verbose_name="Dataset",
            ),
        ),
    ]
