# Generated by Django 5.1.3 on 2025-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0021_alter_diagnosis_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
