# Generated by Django 5.1.3 on 2025-03-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0022_media_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesions',
            fields=[
                ('lesionID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('confidence', models.IntegerField()),
                ('url', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='image.diagnosis')),
            ],
        ),
    ]
