# Generated by Django 5.1.3 on 2025-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0022_media_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="aiModels",
            field=models.TextField(blank=True, verbose_name="Usable AI models"),
        ),
    ]
