# Generated by Django 5.1.3 on 2025-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0023_lesions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesions',
            name='shown',
            field=models.BooleanField(default=True),
        ),
    ]
