# Generated by Django 5.1.3 on 2025-03-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0023_media_aimodels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="aiModels",
        ),
        migrations.CreateModel(
            name="AiModel",
            fields=[
                ("aiModelID", models.AutoField(primary_key=True, serialize=False)),
                ("modelName", models.CharField(max_length=255)),
                ("visibility", models.BooleanField(default=True)),
                (
                    "aiForen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="image.media"
                    ),
                ),
            ],
        ),
    ]
