# Generated by Django 5.1.3 on 2025-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0024_remove_media_aimodels_aimodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aimodel",
            old_name="aiForen",
            new_name="mediaEntry",
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="visibility",
            field=models.BooleanField(default=True, verbose_name="Show doctors model"),
        ),
    ]
