# Generated by Django 5.1.3 on 2025-03-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0025_rename_aiforen_aimodel_mediaentry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="visibility",
            field=models.BooleanField(
                default=True, verbose_name="Show model to doctors"
            ),
        ),
    ]
