# Generated by Django 5.1.3 on 2025-03-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0024_lesions_shown'),
        ('image', '0026_alter_aimodel_visibility'),
    ]

    operations = [
    ]
