# Generated by Django 5.1.3 on 2025-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0027_merge_20250325_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesions',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
