# Generated by Django 5.1.3 on 2025-04-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0028_lesions_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesions',
            name='edited',
            field=models.BooleanField(),
        ),
    ]
