# Generated by Django 5.1.3 on 2025-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0029_alter_lesions_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='confidence',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='confidenceMyDiagnosis',
            field=models.IntegerField(null=True, verbose_name='Confidence for the marked lesions'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='confidenceOfAIdiag',
            field=models.IntegerField(null=True, verbose_name='Confidence to take the AI Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='confidenceOfEditedDiag',
            field=models.IntegerField(null=True, verbose_name='Confidence for the lessions after seeing AI Diagnosis'),
        ),
    ]
