# Generated by Django 5.1.3 on 2025-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0030_remove_diagnosis_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesions',
            name='fromMain',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='confidenceMyDiagnosis',
            field=models.IntegerField(null=True, verbose_name='Confidence for the first diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='confidenceOfEditedDiag',
            field=models.IntegerField(null=True, verbose_name='Confidence for the Edited diagnosis'),
        ),
        migrations.AlterField(
            model_name='lesions',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
